### ISSUE TITLE
Wanting to connect to DVI Heat Pump

### ISSUE THREAD

**Issue by Inrego** [nic6911/ESP32_Modus_Module#14]
Hi there. I'm already using one of these for my Waving floor heating. It's great!
Now, I'm looking to smartify my heat pump, which is a DVI Heat Pump. They've sent me the modbus specifications.

The connector is a DB-9 port. Do you think it would be so simple, that I can just use a cable like this to connect your device to the serial port?
https://www.proshop.dk/Kabler-diverse/Datalogic-CAB-327-RS232-CABLE-CABL/2348820

Or would I have to cut it and join the individual wires to a specific mapping?

**Comment by nic6911** [comment]
Hi, 
That really depends on the layout of that cable and the DVI Heat Pump. You can see the layout of my RJ45 connector here on the repo :) It would be a strike of luck if it just matched 1:1 with Wavin I guess...

**Comment by Inrego** [comment]
I'm just thinking, that since these kinds of cables do exist, there's probably some standardized mapping between the two connectors. So it might not just be luck. But it sounds like you don't necessarily have any knowledge on the subject, so I'll research some more on my own.

**Comment by nic6911** [comment]
Based on my knowledge on Nilan and Wavin (which both can have RJ45 connectors for modbus) I would not expect it to follow any standard. And no, I do not know exactly how that cable you refer to is pinned out and how the DVI unit has it's layout on the DB9 connector :) You'll have to do a little research there on your own :)

**Comment by Inrego** [comment]
I found one of these bad boys. It's arriving today. So time to tinker!
https://www.av-cables.dk/d-sub-stik/terminal-block-adapter-sub-d-9-pin-han-til-til-terminal-block.html
