### ISSUE TITLE
Linked Channels Wavin

### ISSUE THREAD

**Issue by joamla96** [nic6911/ESP32_Modus_Module#3]
In my home I have 2 channels that are linked together on the adjuster in the house.

Short of hiding the secondary channel, and making automation that sync's the two, is there a way to combine them in the software as-is?

**Comment by joamla96** [comment]
Okay, so, after playing around a little more with it, i may have been to quick to open an issue about it.

When I adjust the temperature on the module in the house, it only changes on one of the channels in Home Assistant, so I presume the head unit is handling the linked channel itself.

**Comment by uStepper** [comment]
> Okay, so, after playing around a little more with it, i may have been to quick to open an issue about it.
> 
> When I adjust the temperature on the module in the house, it only changes on one of the channels in Home Assistant, so I presume the head unit is handling the linked channel itself.

You are completely right - the head unit is handling this with combining two outputs and one thermostat. So, in case you have two combined channels you’ll just leave out one of them in the esphome code since it has no thermostat.

**Comment by nic6911** [comment]
You are completely right - the head unit is handling this with combining two outputs and one thermostat. So, in case you have two combined channels you’ll just leave out one of them in the esphome code since it has no thermostat.
