### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by spasserkongen** [nic6911/ESP32_Modus_Module#4]
hvad gør jeg forkert?
jeg har et nilan 300LR, som umiddelbart har stik-forbindelse ligesom på dit readme-billede. Jeg har vedhæftet hvordan jeg har tilslutet ESP-32 modulet til anlægget. Jeg kører 12V udenom da det også drillede.

[logs_nilan_logs(4).txt](https://github.com/nic6911/ESP32_Modus_Module/files/12447694/logs_nilan_logs.4.txt)
![IMG_4053](https://github.com/nic6911/
![Screenshot from 2023-08-27 11-34-17](https://github.com/nic6911/ESP32_Modus_Module/assets/28684092/02473181-afe0-43c1-85ce-1db9b4280a43)
ESP32_Modus_Module/assets/28684092/82012d03-78e1-49b8-861d-9e099c5d8527)

**Comment by spasserkongen** [comment]
![IMG_4053](https://github.com/nic6911/ESP32_Modus_Module/assets/28684092/3d737f47-d897-44b3-869e-d88eb81e821f)

**Comment by nic6911** [comment]
Ud fra billedet så har du enten sat orange til 12v (som modulet vil dø af) eller også sidder dine modbus ledninger et forkert sted hverfald hvis jeg kogger her: https://www.nilan.dk/Files/Files/Dansk/Downloads/3.%20Montagevejledninger/M24_Comfort-300LR_DK.pdfBest regards, MogensDen 27. aug. 2023 kl. 11.38 skrev spasserkongen ***@***.***>:﻿
