### ISSUE TITLE
Change filter Alarm

### ISSUE THREAD

**Issue by nagydavid** [nic6911/ESP32_Modus_Module#6]
Hi Nico, 

I have purchased, from you the ESP32-PICO version. I am using with the Nilan Comfort 300LR and CTS600. Everything is ok, but on the Alarm list in the CTS I am getting and ALARM 91, which is 
|  91  |   I OPT IO          | Optionsprint mangler   | Kontakt service   |

and I cannot clear it.

when I press reset alarms, that does nothing. :(

Maybe you have some suggestion?

p.s.: I just would like to you the set/reset filter alarm

**Comment by nic6911** [comment]
Have you tried the code from the ESP32-C3? There are some changes there. You of course need to adjust the start of the code to match the PICO instead. Else I would suggest trying out the restructured code from Jopand: https://github.com/Jopand/esphome_components/tree/main
