### ISSUE TITLE
Request for help with wiring

### ISSUE THREAD

**Issue by Fredy72** [nic6911/ESP32_Modus_Module#8]
Here it is written about connecting the power supply directly from the CTS602, where, among other things, +12V and GND are output.
> https://github.com/nic6911/ESP32_Modbus_Module/raw/main/electronics/connection.png

Here is a picture of the LILYGO® T-CAN485 wiring in the Nibe heat pump, where PIN9 = GND and PIN12 = +12V (PINs 10 and 11 are Modbus).
> https://github.com/elupus/esphome-nibe/blob/master/examples/lilygo-t-can485.png

I own a LILYGO® T-CAN485 and would like to wiring it up to the CTS602 and powered directly from the CTS602 to the PINs 1,2,3,6.
Pin1 = 12 VDC output
Pin2 = COM1 - RS 485 Data+ (A) - Modbus
Pin3 = COM1 - RS 485 Data- (B) - Modbus
Pin6 = GND

The electrical diagram of the Lily device is as follows.
> https://github.com/Xinyuan-LilyGO/T-CAN485/blob/main/doc/schematic.pdf

I want to ask if it is possible to use the connection in Nilan as pictured with Nibe, i.e. the GND on the RS485 connector (middle PIN) would not be connected (it is written in the first link: "_but keep minimum 1x GND on Nilan in all cases!_")?
Thank you for your answer.

**Comment by nic6911** [comment]
Hi,

![IMG_4993](https://github.com/nic6911/ESP32_Modbus_Module/assets/29756974/fcd06ff6-55ce-42f2-ba78-fe6586537748)

page 4 in the Nilan modbus manual:
https://www.nilan.dk/Files/Files/Dansk/Downloads/7.%20Modbus%20-%20BACnet/2021-01-Modbus_CTS602_w_HMI350T_Modbus.pdf

**Comment by Fredy72** [comment]
Thank you for your response.
So are any of these options correct?
In the picture at Nibe it is like this:
![v1](https://github.com/nic6911/ESP32_Modbus_Module/assets/12939172/579ec11f-98a1-4e46-bebf-cd58ab512528)
As an alternative, I thought of this:
![v2](https://github.com/nic6911/ESP32_Modbus_Module/assets/12939172/110b0f07-52c4-4d01-9b1e-ea473646f912)

**Comment by Fredy72** [comment]
Another way would be to use the USB output from the CTS602 board to USB LilyGo to power the LilyGo. Would it work?

**Comment by nic6911** [comment]
I don't know if the CTS602 has the USB power (or can power back through USB at all) to support that board you have there. With the wiring I can only refer to the doc from Nilan which states that you must use GND. If the GND and RS485GND on the board you have there are tied together I dont know... So the wiring would depend on that.
