### ISSUE TITLE
AHC9000 example code - different versions and missing functionality.

### ISSUE THREAD

**Issue by victordk** [nic6911/ESP32_Modus_Module#9]
Hi

Back in 2022 or early 2023 there was a version 2 of the AHC9000 code that integrated more of heinekmadsens esp components.
It had binary sensors for heat output on the individual strings. The current example code does not have these binary sensors - and i am missing them for some automations. 

Looking through the other examples it resembled the sentio code very much.

Is there any chance we can have a working code example with those binary sensors?

Hope it makes sense.

**Comment by nic6911** [comment]
I have added the V2 example here: esphome_example_code/WavinAHC9000V2_example.yaml
